[package]
name = "bandcompta"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = {version = "0.21.0", features = ["csr"] }
serde = { version = "1.0.219", features = ["derive"] }
wasm-bindgen-futures = "0.4.50"
# serde_rusqlite = "0.38.0"
serde_derive = "1.0.219"
chrono = "0.4.40"
