[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_rusqlite = "0.38.0"
serde_derive = "1.0.219"
chrono = "0.4.40"
tokio = { version = "1.44.2", features = ["full"] }