[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.34.0", features = ["bundled"] }
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_rusqlite = "0.38.0"
serde_derive = "1.0.219"
tokio = { version = "1.44.2", features = ["full"] }
tower-http = { version = "0.6.6", features = ["cors"] }